# Generated by Django 3.2.18 on 2023-03-14 05:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system.user')),
                ('is_student', models.BooleanField(default=True, verbose_name='Aluno')),
                ('course', models.CharField(blank=True, help_text='Nome do curso', max_length=100, verbose_name='Curso')),
                ('period', models.IntegerField(blank=True, default=1, help_text='Período letivo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('system.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AttributeLifeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização')),
                ('name', models.CharField(error_messages={'blank': 'Digite o nome do atributo', 'unique': 'Um atributo com esse nome já existe.'}, help_text='Nome do atributo na tabela de vida', max_length=100, unique=True, verbose_name='Atributo')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='LifeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização')),
                ('name', models.CharField(error_messages={'blank': 'Digite o nome da tabela de vida'}, help_text='Nome da tabela de vida', max_length=100, verbose_name='Nome')),
                ('description', models.CharField(error_messages={'blank': 'Digite a descrição da tabela de vida'}, help_text='Descrição da tabela de vida', max_length=2560, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tabela de vida',
                'verbose_name_plural': 'Tabelas de vida',
            },
        ),
        migrations.CreateModel(
            name='ColumnLifeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifetable.attributelifetable')),
            ],
            options={
                'verbose_name': 'Coluna',
                'verbose_name_plural': 'Colunas',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização')),
                ('value', models.TextField(help_text='Valor da célula da tabela de vida', null=True, verbose_name='Valor')),
                ('line', models.IntegerField(help_text='Linha da célula na tabela de vida', verbose_name='Linha')),
                ('column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifetable.columnlifetable')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifetable.lifetable')),
            ],
            options={
                'verbose_name': 'Célula',
                'verbose_name_plural': 'Células',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização')),
                ('value', models.TextField(help_text='Valor da célula da tabela de vida', null=True, verbose_name='Valor')),
                ('cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifetable.cell')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
    ]
